services:
  marzban_metrics_exporter:
    platform: "linux/arm64" # "linux/amd64"
    # Or use image: ghcr.io/like-a-freedom/rusty_marzban_metrics_exporter:latest
    build: .
    image: rusty_marzban_metrics_exporter
    container_name: rusty_marzban_metrics_exporter
    ports:
      - 8800:8050
    restart: unless-stopped
    environment:
      - URL=http://127.0.0.1:8000 # Marzban API URL, should be in format like http://127.0.0.1:8000
      - USERNAME=admin
      - PASSWORD=admin
      - UPDATE_INTERVAL=30 # Marzban API poll interval in seconds
    healthcheck:
      test: curl http://127.0.0.1:8800/metrics || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 128M
